name: colcon-cmake-ci

on:
  push:
    branches: ['master', 'cottsay/actions']
  pull_request:
    branches: ['*']

jobs:
  pytest:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: [3.6, 3.7, 3.8, 3.9]

    name: colcon-cmake pytest
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python}}
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          python -m pip install -U git+https://github.com/colcon/colcon-core.git
          python -m pip install -U git+https://github.com/colcon/colcon-library-path.git
          python -m pip install -U flake8-blind-except flake8-builtins flake8-class-newline flake8-comprehensions flake8-deprecated flake8-docstrings flake8-import-order flake8-quotes pep8-naming pylint scspell3k
      - name: Run tests
        run: python -m pytest --cov=colcon_cmake --cov-branch
